version: "3.9"

services:
  app:
    build:
      context: .
#    ports:
#      - "5678:8080"
    volumes:
      - ./backend:/app
    restart: on-failure
    command: >
      sh -c "/wait-for-it.sh db:3306 -- java -jar app.jar"

  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=june-2023-java
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=superuser
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf